name: Generate Member Files

on:
  push:
    branches:
      - main # main ブランチへのプッシュ時に実行
  workflow_dispatch: # 手動実行も可能

jobs:
  generate-member-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Execute script
        run: node _member/tools/generateMemberFiles.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
